version: '0'
services:
  ifm-shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_URI
    entrypoint: /bin/bash
    working_dir: /home/
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  ifm:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_URI
    working_dir: /home/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

